name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_trigger:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  triggered_by:
    runs-on: ubunto-latest
    steps:
      - name: event name
        run: echo "trigger_event=${{ github.event_name }}"
