name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  triggered_by:
    runs-on: ubunto-latest
    steps:
      - name: event name
        run: echo "trigger_event=${{ github.event_name }}"
